"""默认风险规则（《10-合同风险规则配置设计》）。

首次全局模板为空时由 bootstrap 幂等写入；四个维度：项目管理/技术/合同条款/通用。
"""
from typing import Any

DEFAULT_RISK_RULES: list[dict[str, Any]] = [
    # ==================== 项目管理风险 ====================
    {
        "code": "PROJECT_SCHEDULE_DELAY",
        "name": "项目进度严重延期风险",
        "category": "project",
        "severity": "high",
        "keywords": ["进度", "延期", "里程碑", "工期", "滞后"],
        "description": "项目计划缺少明确的里程碑、关键路径与延期责任约定，交付节点存在严重延期风险。",
        "suggestion": "明确里程碑、关键路径、延期责任与赶工条款，并约定里程碑验收标准。",
        "enabled": True,
        "sort_order": 10,
    },
    {
        "code": "PROJECT_RANGE_CHANGE",
        "name": "项目范围频繁变更风险",
        "category": "project",
        "severity": "medium",
        "keywords": ["范围", "需求变更", "变更签证", "增项"],
        "description": "需求或范围变更缺少书面确认与费用联动机制，可能导致范围蔓延和成本失控。",
        "suggestion": "约定变更管理流程、书面确认机制、费用与工期调整规则。",
        "enabled": True,
        "sort_order": 20,
    },
    {
        "code": "PROJECT_RESOURCE_SHORTAGE",
        "name": "关键资源投入不足风险",
        "category": "project",
        "severity": "high",
        "keywords": ["人员", "资源", "投入", "驻场", "团队"],
        "description": "合同未明确关键人员、资源投入与替换机制，可能出现投入不足或核心人员流失。",
        "suggestion": "明确关键岗位、驻场要求、人员替换与资源投入保障条款。",
        "enabled": True,
        "sort_order": 30,
    },
    {
        "code": "PROJECT_DELIVERABLE_MISSING",
        "name": "项目交付物缺失风险",
        "category": "project",
        "severity": "medium",
        "keywords": ["交付物", "文档", "验收", "成果", "清单"],
        "description": "交付物清单、验收标准与验收流程不完整，可能导致交付争议。",
        "suggestion": "细化交付物清单、验收标准、验收流程与整改期限。",
        "enabled": True,
        "sort_order": 40,
    },
    # ==================== 技术风险 ====================
    {
        "code": "TECH_LICENSE_COMPLIANCE",
        "name": "开源/第三方许可合规风险",
        "category": "technology",
        "severity": "high",
        "keywords": ["开源", "许可证", "GPL", "商用", "第三方"],
        "description": "使用开源或第三方组件时未评估许可证约束，存在知识产权与商用合规风险。",
        "suggestion": "建立开源/第三方组件清单与许可证合规审查，限制传染性许可证使用。",
        "enabled": True,
        "sort_order": 100,
    },
    {
        "code": "TECH_DATA_SECURITY",
        "name": "数据安全与隐私合规风险",
        "category": "technology",
        "severity": "high",
        "keywords": ["数据", "隐私", "泄露", "加密", "脱敏"],
        "description": "数据存储、传输、访问控制或个人信息保护要求不明确，存在泄露与合规风险。",
        "suggestion": "明确数据分类分级、加密传输、访问控制、脱敏与个人信息保护要求。",
        "enabled": True,
        "sort_order": 110,
    },
    {
        "code": "TECH_PERFORMANCE",
        "name": "系统性能与容量风险",
        "category": "technology",
        "severity": "medium",
        "keywords": ["性能", "并发", "响应时间", "容量", "压测"],
        "description": "未约定性能指标、容量上限与压测验收标准，系统可能无法满足业务要求。",
        "suggestion": "约定P95响应时间、并发数、容量上限、压测场景与验收指标。",
        "enabled": True,
        "sort_order": 120,
    },
    {
        "code": "TECH_MAINTENANCE",
        "name": "技术栈与可维护性风险",
        "category": "technology",
        "severity": "medium",
        "keywords": ["技术栈", "依赖", "版本", "维护", "停止支持"],
        "description": "技术栈、依赖版本或运维责任不明确，可能带来停止支持、维护成本与技术债。",
        "suggestion": "明确技术栈基线、依赖升级策略、运维责任与长期维护承诺。",
        "enabled": True,
        "sort_order": 130,
    },
    # ==================== 合同条款风险 ====================
    {
        "code": "CONTRACT_PAYMENT_ABNORMAL",
        "name": "付款条款异常风险",
        "category": "contract",
        "severity": "high",
        "keywords": ["付款", "支付", "预付款", "货款", "结算"],
        "description": "付款节点、比例、条件或逾期责任约定不清，存在资金与履约风险。",
        "suggestion": "明确付款节点、比例、前提条件、发票要求与逾期付款责任。",
        "enabled": True,
        "sort_order": 200,
    },
    {
        "code": "CONTRACT_BREACH_DUTY",
        "name": "违约责任约定不明风险",
        "category": "contract",
        "severity": "high",
        "keywords": ["违约", "赔偿", "责任", "违约金", "损失"],
        "description": "违约责任、赔偿范围与违约金约定不完整，发生违约时缺少有效追责依据。",
        "suggestion": "明确违约情形、违约金计算、损失赔偿范围与责任上限。",
        "enabled": True,
        "sort_order": 210,
    },
    {
        "code": "CONTRACT_SUBJECT_ILLEGAL",
        "name": "合同主体资质风险",
        "category": "contract",
        "severity": "high",
        "keywords": ["主体", "资质", "营业执照", "授权", "签署人"],
        "description": "合同主体资质、授权或签署人权限未核实，可能导致合同效力问题。",
        "suggestion": "核实主体资质、经营范围、签署人授权与代理权限。",
        "enabled": True,
        "sort_order": 220,
    },
    {
        "code": "CONTRACT_IP_OWNERSHIP",
        "name": "知识产权归属风险",
        "category": "contract",
        "severity": "high",
        "keywords": ["知识产权", "著作权", "专利", "所有权", "成果"],
        "description": "项目成果、软件或文档的知识产权归属与使用许可未约定，存在权属争议。",
        "suggestion": "明确成果归属、许可范围、署名与后续使用边界。",
        "enabled": True,
        "sort_order": 230,
    },
    {
        "code": "CONTRACT_DISPUTE_CLAUSE",
        "name": "争议解决条款缺失风险",
        "category": "contract",
        "severity": "medium",
        "keywords": ["争议", "仲裁", "管辖", "诉讼", "适用法律"],
        "description": "争议解决方式、管辖法院/仲裁机构或适用法律缺失，增加维权成本与不确定性。",
        "suggestion": "明确争议解决方式、管辖机构与适用法律。",
        "enabled": True,
        "sort_order": 240,
    },
    # ==================== 通用风险 ====================
    {
        "code": "GENERAL_FORCE_MAJEURE",
        "name": "不可抗力条款不完整风险",
        "category": "general",
        "severity": "medium",
        "keywords": ["不可抗力", "疫情", "自然灾害", "免责", "通知"],
        "description": "不可抗力的定义、通知义务与后果处理不完整，可能引发履约争议。",
        "suggestion": "明确不可抗力范围、通知时限、证明要求与合同解除/顺延规则。",
        "enabled": True,
        "sort_order": 300,
    },
    {
        "code": "GENERAL_NOTICE_SERVICE",
        "name": "通知与送达条款缺失风险",
        "category": "general",
        "severity": "medium",
        "keywords": ["通知", "送达", "联系人", "地址", "邮箱"],
        "description": "通知方式、送达地址与联系人约定不清，可能导致重要文件未有效送达。",
        "suggestion": "约定通知方式、各方联系人/地址/邮箱及变更通知义务。",
        "enabled": True,
        "sort_order": 310,
    },
    {
        "code": "GENERAL_CONFIDENTIALITY",
        "name": "保密与数据合规风险",
        "category": "general",
        "severity": "high",
        "keywords": ["保密", "数据", "合规", "个人信息", "商业秘密"],
        "description": "保密义务、保密期限与个人信息处理要求不明确，存在商业信息与合规风险。",
        "suggestion": "明确保密范围、期限、违约责任与个人信息处理合规要求。",
        "enabled": True,
        "sort_order": 320,
    },
    {
        "code": "GENERAL_TERMINATION",
        "name": "合同解除与终止风险",
        "category": "general",
        "severity": "medium",
        "keywords": ["解除", "终止", "提前", "退出", "清算"],
        "description": "解除/终止条件、程序与善后义务约定不清，可能造成僵局或损失。",
        "suggestion": "明确解除/终止条件、通知程序、费用清算与交接义务。",
        "enabled": True,
        "sort_order": 330,
    },
]