"""add sys_risk_rule

Revision ID: 5a30eb7586f3
Revises: 5bfa82ffaa60
Create Date: 2026-08-27 22:19:06.224471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a30eb7586f3'
down_revision: Union[str, Sequence[str], None] = '5bfa82ffaa60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_risk_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_risk_rule'))
    )
    op.create_index('ix_sys_risk_rule_category', 'sys_risk_rule', ['category'], unique=False)
    op.create_index('ix_sys_risk_rule_enabled', 'sys_risk_rule', ['enabled'], unique=False)
    op.create_index('ix_sys_risk_rule_severity', 'sys_risk_rule', ['severity'], unique=False)
    op.create_index('uq_sys_risk_rule_code', 'sys_risk_rule', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sys_risk_rule_code', table_name='sys_risk_rule', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_sys_risk_rule_severity', table_name='sys_risk_rule')
    op.drop_index('ix_sys_risk_rule_enabled', table_name='sys_risk_rule')
    op.drop_index('ix_sys_risk_rule_category', table_name='sys_risk_rule')
    op.drop_table('sys_risk_rule')
    # ### end Alembic commands ###
