"""add contract and contract risk

Revision ID: 888645ba003a
Revises: bc198fc2ba29
Create Date: 2026-08-27 23:49:53.793474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '888645ba003a'
down_revision: Union[str, Sequence[str], None] = 'bc198fc2ba29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_contract',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_ext', sa.String(length=16), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('total_chars', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('risk_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name=op.f('fk_sys_contract_user_id_sys_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_contract'))
    )
    op.create_index('ix_sys_contract_created_at', 'sys_contract', ['created_at'], unique=False)
    op.create_index('ix_sys_contract_status', 'sys_contract', ['status'], unique=False)
    op.create_index('ix_sys_contract_user_id', 'sys_contract', ['user_id'], unique=False)
    op.create_table('sys_contract_risk',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('matched_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['sys_contract.id'], name=op.f('fk_sys_contract_risk_contract_id_sys_contract'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name=op.f('fk_sys_contract_risk_user_id_sys_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_contract_risk'))
    )
    op.create_index('ix_sys_contract_risk_contract_id', 'sys_contract_risk', ['contract_id'], unique=False)
    op.create_index('ix_sys_contract_risk_severity', 'sys_contract_risk', ['severity'], unique=False)
    op.create_index('ix_sys_contract_risk_user_id', 'sys_contract_risk', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sys_contract_risk_user_id', table_name='sys_contract_risk')
    op.drop_index('ix_sys_contract_risk_severity', table_name='sys_contract_risk')
    op.drop_index('ix_sys_contract_risk_contract_id', table_name='sys_contract_risk')
    op.drop_table('sys_contract_risk')
    op.drop_index('ix_sys_contract_user_id', table_name='sys_contract')
    op.drop_index('ix_sys_contract_status', table_name='sys_contract')
    op.drop_index('ix_sys_contract_created_at', table_name='sys_contract')
    op.drop_table('sys_contract')
    # ### end Alembic commands ###
