"""add contract risk source

Revision ID: eed395b7bf44
Revises: 888645ba003a
Create Date: 2026-08-28 00:05:06.321157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed395b7bf44'
down_revision: Union[str, Sequence[str], None] = '888645ba003a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_contract_risk', sa.Column('risk_source', sa.String(length=16), server_default='rule', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_contract_risk', 'risk_source')
    # ### end Alembic commands ###
